/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.ngine.math.MathSuite;
	import flexUnitTests.ngine.math.PrimeNumberCase;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_ngine_math_PrimeNumberCase_obj:flexUnitTests.ngine.math.PrimeNumberCase;
		
		private var flexUnitTests_TMathSuite_obj:flexUnitTests.ngine.math.MathSuite;
	}
}